### ISSUE TITLE
Possible Bug with Revo 2.0.1-pl (from git)

### ISSUE THREAD

**Issue by phron** [modmore/CodeMirror#10]
Hello
I noticed a strange behavior of codeMirror 1.1.0 rc1 running on Revo 2.0.1-pl (from Git branch origin/2.0)
I detailed it on the forum http://modxcms.com/forums/index.php/topic,53699.msg310493.html#msg310493...

If you have a bit of time would you be kind to have a quick look at it ?
thanks 
Cheers

**Comment by splittingred** [comment]
The current codemirror version doesn't work on 2.0.1; I have a version that works on 2.0.1 that will be released when 2.0.1 is released.

**Comment by phron** [comment]
Ok :) so there is no problem with my current git install... I was slightly anxious about it, because of this problem with CodeMirror....
Thanks for the feedback
