### ISSUE TITLE
Connect CodeMirror's save action with Modx Save button!

### ISSUE THREAD

**Issue by DominikGuzei** [modmore/CodeMirror#13]
Hi splittingred!

Great plugin, this makes modx finally usable!
One thing would be awesome, if you could connect the codemirror's save callback (standard is crtl/cmd + s) with the modx save button, so that you don't always have to use your mouse to save minor changes, which sucks.

If you don't have time, maybe you know the Modx javascript function to call for this?
kind regards!

**Comment by splittingred** [comment]
This is done in update to CodeMirror 2.
