### ISSUE TITLE
Update request: to latest version of CodeMirror 2

### ISSUE THREAD

**Issue by 01iv3r** [modmore/CodeMirror#14]
update extension to use the latest CodeMirror 2.0

Apologies for the impatient request. splittingred is like the god father of MODx extras and must get a brazillion requests a day.

But the current version of this CodeMirror extra is gettin' glitchy and it is damn handy to have our code highlighted with all the coding done inside the manager, especially adding proper tab  support is key. Issues seem especially prominent in Chrome; grayed out Save button and problems highlighting text. Similar issues in firefox.

Also, support for Zen Coding would be amazing:
http://zen-coding.ru/codemirror/

Man I'm a whiner. I should really just roll up my sleeves and see if I can figure out how to contribute.

**Comment by pixelchutes** [comment]
+1 for CodeMirror v2 request!

ZenCoding would be awesome. I would also love seeing something as simple as the "Active Line Hightlight": http://codemirror.net/demo/activeline.html, "Autoresize Editor": http://codemirror.net/demo/resize.html, or "Search and Replace": http://codemirror.net/demo/search.html demos on the CodeMirror project page.

**Comment by splittingred** [comment]
Update to CodeMirror 2 done. Search and replace is done; active line is done.

ZenCoding is not compatible with CodeMirror 2.
