### ISSUE TITLE
After update to Revo3rev#7058, and codemirror v.1.0.0pl, codemirror doesn't work anymore :(

### ISSUE THREAD

**Issue by phron** [modmore/CodeMirror#3]
Hello Shaun,

I updated Revo to rev7058, and now Codemirror doesn't work anymore. I tried to increase the loader-delay to 900, no change... I also cleared my site cache and my browsers caches, same thing, codemirror doesn't work anymore...
Same behaviour on Chrome and FF, I did not try with IE...

Cheers

**Comment by splittingred** [comment]
Hi anso. It's working fine on mine. What kind of JS errors are you getting?
Do you have the latest CodeMirror?

**Comment by phron** [comment]
Hello Shaun,
I got it ! It works !
What it happened : when I updated codemirror (via Package Management) OR when I updated Revo (via SVN) , the system setting "wich_editor" has been reset to blank (empty) I don't know why but it has... After searching few hours I thought about system setting, the searching by key 'editor' instead of codemirror gave me the solution...
Sorry for this alert.. And thanks again for your great job on Revo...
Cheers

**Comment by phron** [comment]
The culprit system setting was "wich_element_editor" (not "wich_editor" as I wrote previously)

**Comment by splittingred** [comment]
Yeah I need to update CodeMirror's package to set that to CodeMirror on install.
