### ISSUE TITLE
Truncating snippet calls in a chunk

### ISSUE THREAD

**Issue by jrotering** [modmore/CodeMirror#7]
When I create a new chunk w/ CodeMirror set as "which_element_editor", and try to call a snippet, the chunk contents are getting truncated in the middle of the snippet call.

Example chunk:

<div>
[[Wayfinder? &startId=`1` &level=`1`]]
</div>

When I key this in to CodeMirror and save the chunk and reopen it, I get something like
<div>
[[Wayfinder? &start

It seems to be truncating at different places. Not sure if it is based on number of characters w/ a buffer of some sort, or what it might be.

After opening and resaving a few times, it seems like the chunk code will save correctly and then continue to save correctly with any edits... but it is unclear to me what is causing that.  I _can_ recreate this problem repeatedly by creating a new chunk w/ a snippet call in it.

**Comment by splittingred** [comment]
1.1.0 adds some extra checks in this regard, can you try that version?

**Comment by jrotering** [comment]
Seems to work much better with the test cases I tried.  Color coding also now seems more geared toward MODx tag syntax - tag name in black, args in red.  Nice.
