### ISSUE TITLE
Save button greyed out 

### ISSUE THREAD

**Issue by jrotering** [modmore/CodeMirror#8]
Not sure if this is related to the issue I just opened, but I'm experiencing them simultaneously. While editing and saving chunks w/ CodeMirror turned on as the element RTE, sometimes the save button does not "un-grey" when I make changes to the chunk contents.  Have to click outside of codemirror and use Ctrl+Alt+S to save.

**Comment by rtripault** [comment]
Having the same issue here, while clicking outside codemirror "field" doesnt solve the problem. I have to edit pagetitle (or some other "default fields").

**Comment by sirspacey** [comment]
Same problem. I'm using Google Chrome 8.0.552 on MODx Revo 2.0.6.

**Comment by 01iv3r** [comment]
Same problem here as well. Also selecting right to left doesn't work. yet right to left does.

**Comment by splittingred** [comment]
This seems to be fixed with update to CodeMirror 2.
