### ISSUE TITLE
Code doesn't display on first attempt when editing files

### ISSUE THREAD

**Issue by jrotering** [modmore/CodeMirror#9]
When CodeMirror is selected as which_element_editor (Revo 2.0pl), it also becomes the editor for files in the Files tree IF they are left-clicked on rather than right-clicking and choosing "edit file".

The more I think of it, the fact that it works on Files at all is probably an unintentional bug/feature, right?

Anyway, left-clicking on a file opens the file for editing, but the code usually does not display in the CodeMirror area the first time. If you have the file open, then left-click again on that same file in the tree, it seems to always correctly display the file contents in the CodeMirror area.

Windows XP, Chrome & Firefox...

**Comment by splittingred** [comment]
Fixed with update to CodeMirror 2
